### ISSUE TITLE
Add EuroCityPersons (ECP) benchmark

### ISSUE THREAD

**Issue by jkooij** [sunglok/awesome-robotics-datasets#1]
Hi, a new large dataset for detection on pedestrians and other vulnerable road users (e.g. riders on bicycles, mopeds and motorbikes) that can be added:
https://eurocity-dataset.tudelft.nl/

From the website blur:

> The Most Diverse Large Automotive Person Dataset
> 4 seasons, 12 countries, 31 cities, 47.300 images, 238.200 persons.

(disclaimer: its from my group and collaborators)

**Comment by sunglok** [comment]
I have added the recommended dataset at https://github.com/mint-lab/awesome-robotics-datasets/commit/9178fbf066f499f09eaf8dcba86775896852d664. Thank you for your information.
